[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tic_tac_learn"
version = "0.1.2"
description = "Learning agent for tick tac toe game : https://github.com/andrewbeaton123/tic_tac_toe_game "
authors = ["Andrew Beaton"]
packages = [
    { include = "tic_tac_learn", from = "." }
]

[tool.poetry.dependencies]
python = ">3.10"
setuptools= "*"
numpy = "2.2.6"  
mlflow = "3.12.0"
tqdm = "*"
recordclass = "0.24"
safetensors = " 0.7.0"
tic-tac-toe-game = { git = "https://github.com/andrewbeaton123/tic_tac_toe_game.git", rev = "5b47f13a5d2c796b57eb78c64af10212a043395a" }

[tool.poetry.group.test.dependencies]
pytest = "^9.0.3"
pytest-cov = "^7.1.0"
setuptools= "82.0.1"